# Generated by Django 4.1 on 2022-08-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
