# Generated by Django 4.1 on 2022-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='titulo',
            field=models.CharField(default='Documento', max_length=255),
        ),
    ]
