# Generated by Django 4.1 on 2022-08-25 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0006_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='participantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
